# Generated by Django 6.0 on 2025-12-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('Photo', models.ImageField(upload_to='Voter_photos/')),
                ('Voter_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
